export default {
	login: 'AnubhavBharadwaaj',
	id: 23119417,
	node_id: 'MDQ6VXNlcjIxMzYyNDU=',
	avatar_url: 'https://avatars.githubusercontent.com/u/23119417?v=4',
	gravatar_id: '',
	url: 'https://api.github.com/users/AnubhavBharadwaaj',
	html_url: 'https://github.com/AnubhavBharadwaaj',
	followers_url: 'https://api.github.com/users/AnubhavBharadwaaj/followers',
	following_url: 'https://api.github.com/users/AnubhavBharadwaaj/following{/other_user}',
	gists_url: 'https://api.github.com/users/AnubhavBharadwaaj/gists{/gist_id}',
	starred_url: 'https://api.github.com/users/AnubhavBharadwaaj/starred{/owner}{/repo}',
	subscriptions_url: 'https://api.github.com/users/AnubhavBharadwaaj/subscriptions',
	organizations_url: 'https://api.github.com/users/AnubhavBharadwaaj/orgs',
	repos_url: 'https://api.github.com/users/AnubhavBharadwaaj/repos',
	events_url: 'https://api.github.com/users/AnubhavBharadwaaj/events{/privacy}',
	received_events_url: 'https://api.github.com/users/AnubhavBharadwaaj/received_events',
	type: 'User',
	site_admin: false,
	name: 'Anubhav Bharadwaaj',
	company: 'Rupicard',
	blog: 'www.mysterychimp.com',
	location: 'Bangalore, Karnataka',
	email: null,
	hireable: null,
	bio: 'Practice makes perfect',
	twitter_username: 'anubhav27071997',
	public_repos: 19,
	public_gists: 0,
	followers: 0,
	following: 0,
	created_at: "2016-10-28T10:55:44Z",
  	updated_at: "2023-06-09T10:30:19Z"
};
